version: "3"
services:
  gateway:
    build: api-gateway
    ports: 
      - "80:80"
  question-service:
    build: question-service
    ports: 
      - "9090:8080" # TODO: Remove it after configuring gateway.
